


compiler:
- gcc

matrix:
  include:
    - os: linux
      language: python
      sudo: required
      python: 3.5
      install:
        - pip install -r requirements.txt
      script:
        - cd c_code
        - make init
        - cd ../tests
        - python SortingTestSuite.py

    - os: windows
      python: 3.5
      install:
        - pip install -r requirements.txt
      script:
        - cd c_code
        - make init
        - cd ../tests
        - python SortingTestSuite.py


